In [3]:
# Importando PyTorch
import torch

# Introdução ao PyTorch

## O que é PyTorch?
PyTorch é uma biblioteca de aprendizado profundo de código aberto desenvolvida pelo Facebook's AI Research lab (FAIR). Ela é amplamente utilizada para tarefas de visão computacional e processamento de linguagem natural.

### História e contexto
PyTorch foi lançado em janeiro de 2017. Ele é baseado na biblioteca Torch, que é uma estrutura de aprendizado de máquina em Lua. PyTorch é conhecido por sua facilidade de uso e integração com Python, o que o torna popular entre pesquisadores e engenheiros.

### Comparação com outras bibliotecas
- **TensorFlow**: Desenvolvido pelo Google, TensorFlow é uma das bibliotecas de aprendizado profundo mais populares. Enquanto TensorFlow é conhecido por sua escalabilidade e produção, PyTorch é elogiado por sua facilidade de uso e flexibilidade.
- **NumPy**: NumPy é uma biblioteca fundamental para computação científica em Python. PyTorch usa tensores, que são similares aos arrays do NumPy, mas com suporte para computação em GPU.

## O que são tensores?
Tensores são a estrutura de dados fundamental em PyTorch. Eles são similares aos arrays do NumPy, mas com suporte para computação em GPU.

Tensores 1D, 2D, 3D, etc.
- 1D: Vetores
- 2D: Matrizes
- 3D: Matrizes tridimensionais (cubos de dados)
- ND: Tensores de N dimensões

In [ ]:
# Tensor 1D
tensor_1d = torch.tensor([1, 2, 3, 4])
print(tensor_1d)

tensor([1, 2, 3, 4])


In [ ]:
# Tensor 2D
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor_2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Tensor 3D
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_3d)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


### Tipos de dados
Os tensores em PyTorch suportam vários tipos de dados, como inteiros e floats. O tipo de dado pode ser especificado durante a criação do tensor.

In [ ]:
# Criação de um tensor de inteiros
tensor_int = torch.tensor([1, 2, 3], dtype=torch.int32)
print(tensor_int)

tensor([1, 2, 3], dtype=torch.int32)


In [ ]:
# Criação de um tensor de floats
tensor_float = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print(tensor_float)

tensor([1., 2., 3.])


## Funções de Criação de Tensores
PyTorch fornece várias funções utilitárias para criar tensores de forma eficiente.

- `torch.zeros`: Cria um tensor preenchido com zeros.
- `torch.zeros_like`: Cria um tensor preenchido com zeros, com as mesmas dimensões de um tensor dado.
- `torch.ones`: Cria um tensor preenchido com uns.
- `torch.ones_like`: Cria um tensor preenchido com uns, com as mesmas dimensões de um tensor dado.
- `torch.linspace`: Cria um tensor com valores linearmente espaçados entre dois pontos.
- `torch.arange`: Cria um tensor com valores em uma faixa específica com um passo definido.

In [ ]:
# Criação de tensores de zeros
tensor_zeros = torch.zeros(3, 3, 5)
print(tensor_zeros)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [ ]:
# Criação de tensores de zeros_like
tensor_zeros_like = torch.zeros_like(tensor_2d)
print(tensor_zeros_like)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [ ]:
# Criação de tensores de uns
tensor_ones = torch.ones(2, 2)
print(tensor_ones)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Criação de tensores de ones_like
tensor_ones_like = torch.ones_like(tensor_2d)
print(tensor_ones_like)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [ ]:
# Linspace
tensor_linspace = torch.linspace(0, 10, steps=5)
print(tensor_linspace)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [ ]:
# Arange
tensor_arange = torch.arange(0, 10, step=2.5)
print(tensor_arange)

tensor([0.0000, 2.5000, 5.0000, 7.5000])


## Indexação e Fatiamento
A indexação e o fatiamento em PyTorch são similares ao NumPy, permitindo acessar e modificar partes específicas de um tensor.

In [ ]:
# Criando um tensor de exemplo
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Tensor original:\n", tensor)

Tensor original:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
# Indexação por elementos específicos
print("Elemento na posição [1, 2]:", tensor[1, 2])  # Acessa o valor '6'

Elemento na posição [1, 2]: tensor(6)


In [ ]:
# Indexação
print("Primeira linha:", tensor[0, :])  # Obtendo a primeira linha
print("Segunda coluna:", tensor[:, 1])  # Obtendo a segunda coluna

Primeira linha: tensor([1, 2, 3])
Segunda coluna: tensor([2, 5, 8])


In [ ]:
# Fatiamento
print("Subtensor a partir da segunda linha e segunda coluna:\n", tensor[1:, 1:])

Subtensor a partir da segunda linha e segunda coluna:
 tensor([[5, 6],
        [8, 9]])


In [ ]:
# Exemplo de fatiamento complexo: pulando elementos
print("Subtensor pulando uma linha e uma coluna:\n", tensor[::2, ::2])  # Pulando linhas e colunas

Subtensor pulando uma linha e uma coluna:
 tensor([[1, 3],
        [7, 9]])


In [ ]:
# Fatiamento com valores negativos
print("Última linha do tensor:", tensor[-1, :])  # Acessando a última linha
print("Última coluna do tensor:", tensor[:, -1])  # Acessando a última coluna

Última linha do tensor: tensor([7, 8, 9])
Última coluna do tensor: tensor([3, 6, 9])


## Operações básicas com tensores
PyTorch suporta várias operações básicas com tensores, como adição, multiplicação, subtração e divisão.

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Adição
print("+", a + b)

# Multiplicação
print("*", a * b)

# Subtração
print("-", a - b)

# Divisão
print("/", a / b)

# Produto escalar
dot_product = torch.dot(a, b)
print("Produto escalar", dot_product)

+ tensor([5, 7, 9])
* tensor([ 4, 10, 18])
- tensor([-3, -3, -3])
/ tensor([0.2500, 0.4000, 0.5000])
Produto escalar tensor(32)


## Manipulando formato (shape)

In [ ]:
tensor = torch.arange(12).reshape(4, 3) # modifica na memória
print(tensor)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [ ]:
# View
tensor_reshaped = tensor.view(6, 2) # Modifica apenas na tela, apenas para visualização
print(tensor_reshaped)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])


In [ ]:
# Transpose
tensor_transposed = tensor.t()
print(tensor_transposed)

tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])


### Flatten
A função flatten retorna um tensor 1D contendo todos os elementos do tensor original

In [ ]:
# Flatten
tensor_flattened = tensor.flatten()
print(tensor_flattened)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [ ]:
# Reshape
tensor_reshaped = tensor.reshape(1, 2, 6, 1)
print(tensor_reshaped)
print(tensor_reshaped.shape)

tensor([[[[ 0],
          [ 1],
          [ 2],
          [ 3],
          [ 4],
          [ 5]],

         [[ 6],
          [ 7],
          [ 8],
          [ 9],
          [10],
          [11]]]])
torch.Size([1, 2, 6, 1])


### Squeeze e Unsqueeze
- `squeeze`: Remove dimensões de tamanho 1 de um tensor.
- `unsqueeze`: Adiciona uma dimensão de tamanho 1 em um tensor.

In [ ]:
# Squeeze
tensor_squeezed = tensor_reshaped.squeeze()
print(tensor_squeezed)
print(tensor_squeezed.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])


In [ ]:
# Unsqueeze
tensor_unsqueezed = tensor_squeezed.unsqueeze(dim=0)
print(tensor_unsqueezed)
print(tensor_unsqueezed.shape)

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]])
torch.Size([1, 2, 6])


## Broadcasting
O broadcasting é uma técnica que permite que tensores de diferentes formas sejam utilizados juntos em operações aritméticas. Em vez de copiar dados, o PyTorch ajusta os tensores de forma automática para que tenham formas compatíveis.

### Adição de um Escalar

Quando adicionamos um escalar a um tensor, o escalar é automaticamente expandido para a forma do tensor:

In [ ]:
# Cria um tensor 2x3
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Adiciona um escalar
scalar = 10

# Broadcasting para adicionar o escalar a cada elemento do tensor
result = tensor + scalar
print(result)

tensor([[11, 12, 13],
        [14, 15, 16]])


### Adição de Tensores com Diferentes Dimensões

Vamos adicionar um tensor 2x3 com um tensor 1x3. Neste caso, o tensor 1x3 será expandido (broadcasted) para uma forma 2x3:

In [ ]:
# Cria um tensor 2x3
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Cria um tensor 1x3
tensor_b = torch.tensor([10, 20, 30])

# Broadcasting para adicionar tensores de diferentes formas
result = tensor_a + tensor_b
print(result)

tensor([[11, 22, 33],
        [14, 25, 36]])


### Regras de Broadcasting

Para que o broadcasting funcione, os tensores devem seguir algumas regras:

1. **Compatibilidade de Dimensões**: As dimensões dos tensores devem ser compatíveis. Duas dimensões são compatíveis se forem iguais ou se uma delas for 1.
2. **Expansão Automática**: Se uma dimensão de um tensor for 1, ela será expandida para corresponder à dimensão do outro tensor.

No exemplo a seguir, o tensor `tensor_c` de forma 2x1 é expandido para 2x3, e o tensor `tensor_d` de forma 1x3 é expandido para 2x3. O resultado é um tensor 2x3 onde cada elemento é o produto dos elementos correspondentes.

In [ ]:
# Cria um tensor 2x1
tensor_c = torch.tensor([[1], [2]])

# Cria um tensor 1x3
tensor_d = torch.tensor([10, 20, 30])

# Broadcasting para multiplicar tensores de diferentes formas
result = tensor_c * tensor_d
print(result)

tensor([[10, 20, 30],
        [20, 40, 60]])


## Operações de Redução em PyTorch

As operações de redução são usadas para reduzir as dimensões de um tensor, aplicando operações como soma, média, mínimo e máximo. Essas operações são fundamentais em várias aplicações de machine learning e deep learning.

In [ ]:
# Cria um tensor 2x3
tensor = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print("Tensor original:\n", tensor)
print(tensor.shape)

Tensor original:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


### Soma de Todos os Elementos

A função `torch.sum` calcula a soma de todos os elementos do tensor:

In [ ]:
# Soma de todos os elementos do tensor
sum_all = torch.sum(tensor)
print("Soma de todos os elementos:", sum_all.item())

Soma de todos os elementos: 21.0


### Soma ao Longo de um Eixo

Podemos calcular a soma ao longo de um eixo específico, usando o parâmetro `dim`:

In [ ]:
# Soma ao longo do eixo 0 (linhas)
sum_dim0 = torch.sum(tensor, axis=0)
print("Soma ao longo do eixo 0 (linhas):", sum_dim0)
print(sum_dim0.shape)

Soma ao longo do eixo 0 (linhas): tensor([5., 7., 9.])
torch.Size([3])


In [ ]:
# Soma ao longo do eixo 1 (colunas)
sum_dim1 = torch.sum(tensor, dim=1)
print("Soma ao longo do eixo 1 (colunas):", sum_dim1)
print(sum_dim1.shape)

Soma ao longo do eixo 1 (colunas): tensor([ 6., 15.])
torch.Size([2])


### Média dos Elementos

A função `torch.mean` calcula a média dos elementos do tensor:

In [ ]:
# Média de todos os elementos do tensor
mean_all = torch.mean(tensor)
print("Média de todos os elementos:", mean_all.item())

Média de todos os elementos: 3.5


In [ ]:
# Média ao longo do eixo 0 (linhas)
mean_dim0 = torch.mean(tensor, dim=0)
print("Média ao longo do eixo 0 (linhas):", mean_dim0)
print(mean_dim0.shape)

Média ao longo do eixo 0 (linhas): tensor([2.5000, 3.5000, 4.5000])
torch.Size([3])


In [ ]:
# Média ao longo do eixo 1 (colunas)
mean_dim1 = torch.mean(tensor, dim=1)
print("Média ao longo do eixo 1 (colunas):", mean_dim1)
print(mean_dim1.shape)

Média ao longo do eixo 1 (colunas): tensor([2., 5.])
torch.Size([2])


### Valor Mínimo e Máximo

Podemos encontrar o valor mínimo e máximo de um tensor usando `torch.min` e `torch.max`:

In [ ]:
# Valor mínimo de todos os elementos do tensor
min_all = torch.min(tensor)
print("Valor mínimo de todos os elementos:", min_all)
print()

# Valor máximo de todos os elementos do tensor
max_all = torch.max(tensor)
print("Valor máximo de todos os elementos:", max_all)
print()

# Valor mínimo ao longo do eixo 0 (linhas)
min_dim0, min_indices_dim0 = torch.min(tensor, dim=0)
print("Valor mínimo ao longo do eixo 0 (linhas):", min_dim0)
print("Índices dos valores mínimos ao longo do eixo 0 (linhas):", min_indices_dim0)
print()

# Valor máximo ao longo do eixo 1 (colunas)
max_dim1, max_indices_dim1 = torch.max(tensor, dim=1)
print("Valor máximo ao longo do eixo 1 (colunas):", max_dim1)
print("Índices dos valores máximos ao longo do eixo 1 (colunas):", max_indices_dim1)

Valor mínimo de todos os elementos: tensor(1.)

Valor máximo de todos os elementos: tensor(6.)

Valor mínimo ao longo do eixo 0 (linhas): tensor([1., 2., 3.])
Índices dos valores mínimos ao longo do eixo 0 (linhas): tensor([0, 0, 0])

Valor máximo ao longo do eixo 1 (colunas): tensor([3., 6.])
Índices dos valores máximos ao longo do eixo 1 (colunas): tensor([2, 2])


### Produto dos Elementos

A função `torch.prod` calcula o produto de todos os elementos do tensor:

In [ ]:
# Produto de todos os elementos do tensor
prod_all = torch.prod(tensor)
print("Produto de todos os elementos:", prod_all)
print()

# Produto ao longo do eixo 0 (linhas)
prod_dim0 = torch.prod(tensor, dim=0)
print("Produto ao longo do eixo 0 (linhas):", prod_dim0)
print()

# Produto ao longo do eixo 1 (colunas)
prod_dim1 = torch.prod(tensor, dim=1)
print("Produto ao longo do eixo 1 (colunas):", prod_dim1)

Produto de todos os elementos: tensor(720.)

Produto ao longo do eixo 0 (linhas): tensor([ 4., 10., 18.])

Produto ao longo do eixo 1 (colunas): tensor([  6., 120.])


## Propriedade requires_grad
A propriedade `requires_grad` em PyTorch é fundamental para a construção e treinamento de redes neurais, pois permite calcular automaticamente os gradientes das operações. Quando `requires_grad` é definido como `True` em um tensor, todas as operações feitas nesse tensor serão rastreadas para a diferenciação automática.

### Autograd e Grafos Computacionais

Autograd é um componente essencial em frameworks de deep learning como PyTorch, que permite a diferenciação automática de tensores. Este mecanismo é fundamental para a otimização dos modelos de aprendizado de máquina, pois permite calcular gradientes de forma eficiente, necessária para o ajuste dos parâmetros do modelo durante o treinamento.

#### Grafos Computacionais

Para entender o funcionamento do autograd, é importante compreender os grafos computacionais. Um grafo computacional é uma representação gráfica de uma sequência de operações matemáticas, onde:

- **Nós (nodes)** representam operações matemáticas ou variáveis.
- **Arestas (edges)** representam os fluxos de dados (tensores) entre as operações.

![alt text](https://miro.medium.com/max/908/1*ahiviCqq6B0R_XWBmgvHkA.png "Grafo Computacional")

Durante a construção de um modelo, as operações realizadas nos tensores criam um grafo computacional dinâmico, também conhecido como *Dynamic Computation Graph*. Esse grafo é dinâmico porque é construído à medida que as operações são executadas, permitindo flexibilidade e facilidade na criação e modificação de modelos.

#### Propagação para Frente (Forward Pass)

Durante a propagação para frente (forward pass), os tensores são passados através das operações definidas no grafo computacional, produzindo uma saída. Este processo é usado para calcular a perda (loss) do modelo.

#### Propagação para Trás (Backward Pass)

A propagação para trás (backward pass) é o processo de calcular os gradientes dos tensores em relação à perda, utilizando a regra da cadeia. O autograd facilita essa tarefa, realizando automaticamente a diferenciação reversa ao longo do grafo computacional. Os passos são:

1. **Calcula a perda**: A partir das saídas do forward pass.
2. **Calcula os gradientes**: Utilizando a diferenciação automática.
3. **Atualiza os parâmetros**: Os gradientes calculados são usados para ajustar os parâmetros do modelo através de otimização, como o gradiente descendente.

### Criando Tensores com `requires_grad`

Vamos criar tensores com a propriedade `requires_grad` definida como `True`:

In [ ]:
# Tensor com requires_grad
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(x)

tensor([1., 2., 3.], requires_grad=True)


### Realizando Operações com Tensores que Têm `requires_grad`

Quando realizamos operações com tensores que têm `requires_grad=True`, o PyTorch cria uma tape (fita) para rastrear todas as operações. Vamos ver um exemplo:

In [ ]:
# Realiza uma operação com o tensor x
y = x ** 2

# Mais uma operação
z = y.sum()

print(z)

tensor(14., grad_fn=<SumBackward0>)


### Calculando Gradientes

Para calcular os gradientes, usamos o método `backward()`. Isso calcula o gradiente da função de perda em relação a todos os tensores que têm `requires_grad=True`.

Os gradientes armazenados em `x.grad` representam a derivada da soma `z` em relação a `x`. Como `z` é a soma dos elementos de `y` e `y = x ** 2`, a derivada de `z` em relação a `x` é `2 * x`.

In [ ]:
# Calcula os gradientes
z.backward()

# z = x1² + x2² + x3²
# dz/x1 = 2x1

# Imprime os gradientes armazenados em x.grad
print(x.grad)

tensor([2., 4., 6.])


### Desativando o Rastreamento de Gradientes

Em algumas situações, não queremos rastrear as operações, como durante a inferência do modelo. Podemos desativar temporariamente o rastreamento de gradientes usando `torch.no_grad()` ou `detach()`. Vamos ver como:

In [ ]:
# Desativando o rastreamento de gradientes temporariamente
with torch.no_grad():
    y = x * 2
    print(y.requires_grad)  # False, pois o rastreamento está desativado

# Criando um novo tensor sem rastreamento de gradientes
x_detached = x.detach()
print(x_detached.requires_grad)  # False, pois o tensor foi separado da tape de computação

False
False


### Verificando se um Tensor Requer Gradiente

Podemos verificar se um tensor requer gradiente usando a propriedade `requires_grad`:

In [ ]:
print(x.requires_grad)  # True, pois x foi criado com requires_grad=True
print(x_detached.requires_grad)  # False, pois x_detached foi separado da tape de computação

True
False


## Exercícios - PyTorch Básico

# Exercício 1: Criação de Tensores

1. Crie um tensor 1D com os valores de 1 a 10.
2. Crie um tensor 2D de forma (3, 3) com valores aleatórios.
3. Crie um tensor 3D de forma (2, 3, 4) com todos os valores iguais a 1.
4. Crie um tensor de zeros com as mesmas dimensões do tensor 2D criado no exercício 2.
5. Crie um tensor de uns com as mesmas dimensões do tensor 3D criado no exercício 3.

In [8]:
# 1. Crie um tensor 1D com os valores de 1 a 10.
tensor_1 = torch.arange(1, 11)
print(tensor_1)
print()

# 2. Crie um tensor 2D de forma (3, 3) com valores aleatórios.
tensor_2 = torch.rand(3, 3) * 10
print(tensor_2)
print()

# 3. Crie um tensor 3D de forma (2, 3, 4) com todos os valores iguais a 1.
tensor_3 = torch.ones(2, 3, 4)
print(tensor_3)
print()

# 4. Crie um tensor de zeros com as mesmas dimensões do tensor 2D criado no exercício 2.
tensor_4 = torch.zeros_like(tensor_2)
print(tensor_4)
print()

# 5. Crie um tensor de uns com as mesmas dimensões do tensor 3D criado no exercício 3.
tensor_5 = torch.ones_like(tensor_3)
print(tensor_5)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

tensor([[5.5303, 4.2286, 5.3975],
        [0.5012, 8.2671, 7.8071],
        [4.3975, 5.0747, 0.6563]])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


### Exercício 2: Manipulação de Tensores

1. Dado o tensor `a = torch.tensor([[1, 2], [3, 4], [5, 6]])`, obtenha a primeira coluna.
2. Dado o tensor `b = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])`, obtenha o subtensor `[[7, 8, 9], [10, 11, 12]]`.
3. Dado o tensor `c = torch.tensor([1, 2, 3, 4, 5, 6])`, mude sua forma para (2, 3).
4. Dado o tensor `d = torch.tensor([1, 2, 3, 4, 5, 6])`, adicione uma dimensão extra para que ele se torne de forma (1, 6).

In [12]:
# Exercício 1 - Obtenha a primeira coluna
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
print("Primeira coluna:", a[:, 0])
print()

# Exercício 2 - Obter o subtensor [[7, 8, 9], [10, 11, 12]]
b = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Subtensor:", b[-1, :, :])
print()

# Exercício 3 - Mude a forma de c para (2, 3)
c = torch.tensor([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print("Tensor reshape para (2, 3):\n", c)
print()

# Exercício 4 - Adicionar uma dimensão extra para que d tenha a forma (1, 6)
d = torch.tensor([1, 2, 3, 4, 5, 6])
print("Com dimensão extra (1, 6):\n", d.unsqueeze(0))
print("Forma do tensor:", d.unsqueeze(0).shape)


Primeira coluna: tensor([1, 3, 5])

Subtensor: tensor([[ 7,  8,  9],
        [10, 11, 12]])

Tensor reshape para (2, 3):
 tensor([[1, 2, 3],
        [4, 5, 6]])

Com dimensão extra (1, 6):
 tensor([[1, 2, 3, 4, 5, 6]])
Forma do tensor: torch.Size([1, 6])


### Exercício 3: Funções de Criação de Tensores

1. Crie um tensor contendo valores de 0 a 1, espaçados igualmente em 5 passos.
2. Crie um tensor contendo valores de 0 a 10, com um passo de 2.
3. Crie um tensor de forma (3, 3) com valores aleatórios entre 0 e 10.
4. Crie um tensor correspondente a uma imagem em escala de cinza de dimensões 128x128 com valores aleatórios entre 0 e 255.
5. Crie um tensor correspondente a uma imagem em RGB de dimensões 128x128 com valores aleatórios entre 0 e 255.

In [18]:
# 1. Crie um tensor contendo valores de 0 a 1, espaçados igualmente em 5 passos.
tensor1 = torch.linspace(0, 1, steps=5)
print(tensor1)
print()

# 2. Crie um tensor contendo valores de 0 a 10, com um passo de 2.
tensor2 = torch.arange(0, 10, step=2)
print(tensor2)
print()

# 3. Crie um tensor de forma (3, 3) com valores aleatórios entre 0 e 10.
tensor3 = torch.rand(3, 3) * 10
print(tensor3)
print()

#4. Crie um tensor correspondente a uma imagem em escala de cinza de dimensões 128x128 com valores aleatórios entre 0 e 255.
gray_image_tensor = torch.randint(0, 256, (128, 128), dtype=torch.uint8)
print(gray_image_tensor)
print()

# 5. Crie um tensor correspondente a uma imagem em RGB de dimensões 128x128 com valores aleatórios entre 0 e 255.
rgb_image_tensor = torch.randint(0, 256, (128, 128, 3), dtype=torch.uint8)
print(rgb_image_tensor)
print()

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

tensor([0, 2, 4, 6, 8])

tensor([[4.3584, 3.9818, 6.3911],
        [4.8523, 7.2087, 0.0665],
        [5.3503, 7.2154, 6.8402]])

tensor([[159,  59, 125,  ...,   6, 226, 227],
        [162, 126, 122,  ...,  39, 125, 245],
        [254, 174,  44,  ..., 137,  12, 126],
        ...,
        [ 57,  20,  87,  ...,  71,  31,  53],
        [232,  99, 244,  ..., 222,   3, 165],
        [ 39,  57, 123,  ...,  39,  78,  46]], dtype=torch.uint8)

tensor([[[ 24, 132,  20],
         [ 27, 191,  67],
         [  2, 172, 233],
         ...,
         [199, 147,  55],
         [149,  45, 203],
         [ 94,  79, 218]],

        [[ 22, 226,  20],
         [245, 206,  43],
         [206, 129, 123],
         ...,
         [210, 237, 236],
         [ 80, 211,  14],
         [132, 191, 138]],

        [[116, 221, 195],
         [238, 245, 186],
         [ 75, 184, 217],
         ...,
         [  0,  13, 113],
         [244, 199, 154],
         [ 99, 176, 107

### Exercício 4: Operações Avançadas com Tensores

1. Dado o tensor `a = torch.tensor([1, 2, 3])` e `b = torch.tensor([[4], [5], [6]])`, calcule a soma de `a` e `b` usando broadcasting.
2. Dado o tensor `a = torch.tensor([1.0, 2.0, 3.0, 4.0])`, calcule a soma de todos os elementos.
3. Dado o tensor `a = torch.tensor([1.0, 2.0, 3.0, 4.0])`, calcule a média de todos os elementos.
4. Dado o tensor `a = torch.tensor([1.0, 2.0, 3.0, 4.0])`, calcule a raiz quadrada de todos os elementos.

In [22]:
# 1. Dado o tensor a = torch.tensor([1, 2, 3]) e b = torch.tensor([[4], [5], [6]]), calcule a soma de a e b usando broadcasting.
a = torch.tensor([1, 2, 3])
b = torch.tensor([[4], [5], [6]])
result_1 = a + b
print(result_1)
print()

# 2. Dado o tensor a = torch.tensor([1.0, 2.0, 3.0, 4.0]), calcule a soma de todos os elementos.
a = torch.tensor([1.0, 2.0, 3.0, 4.0])
soma = torch.sum(a)
print("Soma de todos os elementos:", soma.item())
print()

# 3. Dado o tensor a = torch.tensor([1.0, 2.0, 3.0, 4.0]), calcule a média de todos os elementos.
a = torch.tensor([1.0, 2.0, 3.0, 4.0])
media = torch.mean(a)
print("Média de todos os elementos:", media.item())
print()

# 4. Dado o tensor a = torch.tensor([1.0, 2.0, 3.0, 4.0]), calcule a raiz quadrada de todos os elementos.
a = torch.tensor([1.0, 2.0, 3.0, 4.0])
raiz_quadrada = torch.sqrt(a)
print("Raiz quadrada de todos os elementos:", raiz_quadrada)

tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])

Soma de todos os elementos: 10.0

Média de todos os elementos: 2.5

Raiz quadrada de todos os elementos: tensor([1.0000, 1.4142, 1.7321, 2.0000])


### Exercício 5: Autograd e Backpropagation

1. Crie um tensor `x` com os valores `[2.0, 3.0]` e `requires_grad=True`. Calcule `y = x^2` e os gradientes.
2. Crie um tensor `x` com o valor `3.0` e `requires_grad=True`. Calcule `y = 2*x + 1` e o gradiente.
3. Crie um tensor `x` com os valores `[1.0, 2.0, 3.0]` e `requires_grad=True`. Calcule `y = x^3` e os gradientes.

In [26]:
# 1. Crie um tensor x com os valores [2.0, 3.0] e requires_grad=True. Calcule y = x^2 e os gradientes.
x1 = torch.tensor([2.0, 3.0], requires_grad=True)
y1 = x1 ** 2
z1 = y1.sum()
print(z1)
z1.backward()
print(x1.grad)
print()

# 2. Crie um tensor x com o valor 3.0 e requires_grad=True. Calcule y = 2*x + 1 e o gradiente.
x2 = torch.tensor([3.0], requires_grad=True)
y2 = 2*x2 + 1
z2 = y2.sum()
print(z2)
z2.backward()
print(x2.grad)
print()

# 3. Crie um tensor x com os valores [1.0, 2.0, 3.0] e requires_grad=True. Calcule y = x^3 e os gradientes
x3 = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y3 = x3 ** 3
z3 = y3.sum()
print(z3)
z3.backward()
print(x3.grad)

tensor(13., grad_fn=<SumBackward0>)
tensor([4., 6.])

tensor(7., grad_fn=<SumBackward0>)
tensor([2.])

tensor(36., grad_fn=<SumBackward0>)
tensor([ 3., 12., 27.])


### Exercício 6: Operações de Redução

1. Crie um tensor de forma (4, 5) contendo valores de 1 a 20 usando `torch.arange`. Em seguida, calcule a soma de todos os elementos do tensor.

2. Crie um tensor de forma (3, 4) com valores aleatórios entre 0 e 1 usando `torch.rand`. Calcule a média dos elementos ao longo do eixo 1 (colunas).

3. Crie um tensor de forma (5, 5) contendo valores espaçados igualmente de 0 a 24 usando `torch.linspace`. Encontre o valor mínimo e o máximo de todos os elementos do tensor.

4. Crie um tensor de forma (3, 6) com valores inteiros aleatórios entre 10 e 50 usando `torch.randint`. Calcule o produto dos elementos ao longo do eixo 0 (linhas).

5. Crie um tensor de forma (2, 3, 4) com valores aleatórios entre 0 e 1 usando `torch.rand`. Encontre a soma dos elementos ao longo do eixo 2.

In [34]:
# 1. Crie um tensor de forma (4, 5) contendo valores de 1 a 20 usando `torch.arange`. Em seguida, calcule a soma de todos os elementos do tensor.
t_1 = torch.arange(1, 21).reshape(4, 5)
print(t_1)
print()
print('Soma dos elementos: ', t_1.sum())
print('--------------------------------------')
print()


# 2. Crie um tensor de forma (3, 4) com valores aleatórios entre 0 e 1 usando `torch.rand`. Calcule a média dos elementos ao longo do eixo 1 (colunas).
t_2 = torch.rand(3, 4)
print(t_2)
print()
print('Média dos elementos: ', t_2.mean(dim=1))
print('--------------------------------------')
print()


# 3. Crie um tensor de forma (5, 5) contendo valores espaçados igualmente de 0 a 24 usando `torch.linspace`. Encontre o valor mínimo e o máximo de todos os elementos do tensor.
t_3 = torch.linspace(0, 24, steps=25).reshape(5, 5)
print(t_3)
print()
print('Valor mínimo: ', t_3.min())
print('Valor máximo: ', t_3.max())
print('--------------------------------------')
print()

# 4. Crie um tensor de forma (3, 6) com valores inteiros aleatórios entre 10 e 50 usando `torch.randint`. Calcule o produto dos elementos ao longo do eixo 0 (linhas).
t_4 = torch.randint(10, 50, (3, 6))
print(t_4)
print()
print("Produto ao longo do eixo 0 (linhas):", torch.prod(t_4, dim=0))
print('--------------------------------------')
print()

# 5. Crie um tensor de forma (2, 3, 4) com valores aleatórios entre 0 e 1 usando `torch.rand`. Encontre a soma dos elementos ao longo do eixo 2.
t_5 = torch.rand(2, 3, 4)
print(t_5)
print()
print("Soma ao longo do eixo 2:", torch.sum(t_5, dim=2))

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

Soma dos elementos:  tensor(210)
--------------------------------------

tensor([[0.9141, 0.7329, 0.5812, 0.2099],
        [0.4790, 0.3917, 0.0464, 0.5887],
        [0.2213, 0.6680, 0.6927, 0.7792]])

Média dos elementos:  tensor([0.6095, 0.3765, 0.5903])
--------------------------------------

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]])

Valor mínimo:  tensor(0.)
Valor máximo:  tensor(24.)
--------------------------------------

tensor([[16, 40, 33, 10, 24, 45],
        [29, 43, 38, 31, 31, 30],
        [28, 10, 15, 42, 24, 44]])

Produto ao longo do eixo 0 (linhas): tensor([12992, 17200, 18810, 13020, 17856, 59400])
--------------------------------------

tensor([[[0.8433, 0.3041, 0.8861, 0.2404],
         [0.9450, 0.3172, 0.2442, 0.0